# Generated by Django 3.0.5 on 2021-03-09 02:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workbooks.Chapter'),
        ),
        migrations.AddField(
            model_name='question',
            name='commentary_image_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=[], size=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=[], size=10),
        ),
    ]
