# Generated by Django 3.0.5 on 2021-03-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0002_auto_20210309_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='章識別子'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='問題識別子'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('chapter_id', 'workbook')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question_id', 'workbook')},
        ),
    ]
