# Generated by Django 3.0.5 on 2021-03-09 02:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0003_auto_20210309_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='commentary_image_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=10),
        ),
    ]
