# Generated by Django 3.0.5 on 2021-03-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0004_auto_20210309_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='done',
            field=models.BooleanField(default=False, verbose_name='実施完了済みか'),
        ),
    ]
