# Generated by Django 3.0.5 on 2021-09-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0006_auto_20210907_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_type',
            field=models.TextField(choices=[('RAND', 'Random'), ('CHAP', 'Select Chapter'), ('MIST', 'Review Mistake')], default='RAND', max_length=4, verbose_name='実施種別'),
        ),
    ]
