# Generated by Django 3.0.5 on 2021-09-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0007_auto_20210908_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='index',
            field=models.IntegerField(db_index=True, default=1, verbose_name='並び順'),
        ),
        migrations.AddField(
            model_name='question',
            name='index',
            field=models.IntegerField(db_index=True, default=1, verbose_name='並び順'),
        ),
    ]
