# Generated by Django 3.0.5 on 2021-09-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0008_auto_20210909_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_type',
            field=models.TextField(choices=[('RAND', 'Random'), ('CHAP', 'Select Chapter'), ('MIST', 'Review Mistake'), ('ORDR', 'Ordered')], default='RAND', max_length=4, verbose_name='実施種別'),
        ),
    ]
