# Generated by Django 3.0.5 on 2021-10-13 06:44

from django.db import migrations, models
import django.db.models.deletion
import livefield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0011_auto_20210924_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('live', livefield.fields.LiveField(blank=True, default=True, null=True)),
                ('training_question_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='出題問題ID')),
                ('index', models.IntegerField(db_index=True, default=1, verbose_name='並び順')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workbooks.Question')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workbooks.Training')),
            ],
            options={
                'verbose_name': 'training_questions',
                'verbose_name_plural': 'TrainingQuestion',
            },
        ),
    ]
