# Generated by Django 3.0.5 on 2021-10-23 07:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0012_trainingquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='live',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='live',
        ),
        migrations.RemoveField(
            model_name='question',
            name='live',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='live',
        ),
        migrations.RemoveField(
            model_name='training',
            name='live',
        ),
        migrations.RemoveField(
            model_name='trainingchapter',
            name='live',
        ),
        migrations.RemoveField(
            model_name='trainingquestion',
            name='live',
        ),
        migrations.RemoveField(
            model_name='trainingselection',
            name='live',
        ),
        migrations.RemoveField(
            model_name='workbook',
            name='live',
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('question_group_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='問題グループID')),
                ('title', models.CharField(db_index=True, max_length=250, verbose_name='タイトル')),
                ('description', models.TextField(verbose_name='問題説明文')),
                ('workbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workbooks.Workbook')),
            ],
            options={
                'verbose_name': 'question_groups',
                'verbose_name_plural': 'QuestionGroup',
            },
        ),
    ]
