# Generated by Django 3.0.5 on 2021-11-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0015_auto_20211101_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='公開する'),
        ),
    ]
