# Generated by Django 3.0.5 on 2021-11-01 11:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0016_workbook_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='workbook_id',
        ),
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='カテゴリ識別子'),
        ),
    ]
