# Generated by Django 3.0.5 on 2021-11-05 04:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0017_auto_20211101_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='image_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='カテゴリー画像'),
        ),
    ]
