# Generated by Django 3.0.5 on 2021-11-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0019_auto_20211108_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='default_answer_count',
            field=models.IntegerField(default=4, verbose_name='回答選択肢の数'),
        ),
    ]
