# Generated by Django 3.0.5 on 2021-11-10 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0021_questiongroup_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiongroup',
            old_name='description',
            new_name='sentense',
        ),
    ]
