# Generated by Django 3.0.5 on 2021-11-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0022_auto_20211110_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='sentense',
            field=models.TextField(blank=True, default='', verbose_name='問題文'),
        ),
    ]
