# Generated by Django 3.0.5 on 2021-11-15 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0024_auto_20211115_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcarddeck',
            name='user',
        ),
        migrations.DeleteModel(
            name='FlashCard',
        ),
        migrations.DeleteModel(
            name='FlashCardDeck',
        ),
    ]
