# Generated by Django 3.0.5 on 2021-12-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0025_auto_20211115_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='passing_score',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='合格点'),
        ),
        migrations.AddField(
            model_name='training',
            name='question_count',
            field=models.IntegerField(default=10, verbose_name='問題数'),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_type',
            field=models.TextField(choices=[('RAND', 'Random'), ('CHAP', 'Select Chapter'), ('MIST', 'Review Mistake'), ('ORDR', 'Ordered'), ('EXAM', 'Exam')], default='RAND', max_length=4, verbose_name='実施種別'),
        ),
    ]
